modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="pixelmonpartystats"
version="1.0.0"
displayName="Pixelmon Party Stats"
displayURL="https://github.com/NebuloSystemServices"
credits="https://github.com/NebuloSystemServices"
authors="https://github.com/NebuloSystemServices"
description='''
A mod that adds a command to view the stats of all the pokemon in your party.
'''

[[dependencies.pixelmonpartystats]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pixelmonpartystats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"


[[dependencies.pixelmonpartystats]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.3,)"
    ordering="NONE"
    side="BOTH"